import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronLeft, ChevronRight, RefreshCw, Search, XCircle } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { StatusAlert } from '@/components/StatusAlert';
import { auditEndpoint } from '@/lib/gateway';
import { requestJson } from '@/lib/http';
import type { AuditListResponse } from '@/types';

const PAGE_SIZE = 20;
export default function AuditPage() {
  const [data, setData] = useState<AuditListResponse>({ total: 0, limit: PAGE_SIZE, offset: 0, entries: [] }); const [tool, setTool] = useState(''); const [status, setStatus] = useState(''); const [offset, setOffset] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setData(await requestJson<AuditListResponse>(auditEndpoint({ limit: PAGE_SIZE, offset, tool: tool.trim() || undefined, resultStatus: status || undefined }))); setError(null); } catch (err) { setError(err instanceof Error ? err.message : '审计日志加载失败'); } finally { setLoading(false); } }, [offset, status, tool]);
  useEffect(() => { const timer = window.setTimeout(load, tool ? 250 : 0); return () => window.clearTimeout(timer); }, [load, tool]);
  const page = Math.floor(offset / PAGE_SIZE) + 1; const pages = Math.max(1, Math.ceil(data.total / PAGE_SIZE));
  const summary = useMemo(() => ({ success: data.entries.filter((entry) => entry.result_status === 'success').length, failure: data.entries.filter((entry) => entry.result_status === 'failure').length }), [data.entries]);
  return <div><PageHeader title="工具调用审计" description="追踪工具请求、脱敏参数、执行结果与耗时" actions={<button onClick={load} className="button-secondary" disabled={loading}><RefreshCw size={14} className={loading ? 'animate-spin' : ''} />刷新</button>} />
    {error ? <div className="mb-4"><StatusAlert message={error} onRetry={load} onDismiss={() => setError(null)} /></div> : null}
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><div className="surface-panel p-4"><div className="text-[10px] font-medium text-crt-fg-muted">记录总数</div><div className="mt-1 text-xl font-semibold tabular-nums">{data.total}</div></div><div className="surface-panel p-4"><div className="text-[10px] font-medium text-crt-fg-muted">本页成功</div><div className="mt-1 text-xl font-semibold text-crt-green tabular-nums">{summary.success}</div></div><div className="surface-panel p-4"><div className="text-[10px] font-medium text-crt-fg-muted">本页失败</div><div className="mt-1 text-xl font-semibold text-crt-red tabular-nums">{summary.failure}</div></div></div>
    <div className="surface-panel overflow-hidden"><div className="flex flex-col gap-2 border-b border-crt-border p-3 sm:flex-row"><label className="relative flex-1"><Search size={14} className="absolute left-3 top-2.5 text-crt-fg-muted" /><input className="field-control h-9 pl-9 text-[11px]" value={tool} onChange={(e) => { setTool(e.target.value); setOffset(0); }} placeholder="按工具名称筛选" /></label><select className="field-control h-9 sm:w-40" value={status} onChange={(e) => { setStatus(e.target.value); setOffset(0); }}><option value="">全部结果</option><option value="success">成功</option><option value="failure">失败</option></select></div>
      <div className="overflow-x-auto"><table><thead><tr className="bg-crt-bg"><th className="px-4 py-3">时间</th><th className="px-4 py-3">工具 / Agent</th><th className="px-4 py-3">结果</th><th className="px-4 py-3">耗时</th><th className="px-4 py-3">摘要</th><th className="px-4 py-3">Trace</th></tr></thead><tbody>{loading ? Array.from({ length: 5 }).map((_, i) => <tr key={i} className="border-t border-crt-border"><td colSpan={6} className="px-4 py-4"><div className="skeleton h-5" /></td></tr>) : data.entries.map((entry) => <tr key={entry.audit_id} className="border-t border-crt-border hover:bg-crt-bg"><td className="whitespace-nowrap px-4 py-3 text-[10px]">{new Date(entry.timestamp).toLocaleString('zh-CN')}</td><td className="px-4 py-3"><div className="text-[11px] font-semibold text-crt-fg">{entry.tool_name}</div><div className="text-[9px] text-crt-fg-muted">{entry.agent_name || '通用 Agent'}</div></td><td className="px-4 py-3">{entry.result_status === 'success' ? <span className="inline-flex items-center gap-1 text-[10px] font-medium text-crt-green"><CheckCircle2 size={13} />成功</span> : <span className="inline-flex items-center gap-1 text-[10px] font-medium text-crt-red"><XCircle size={13} />失败</span>}</td><td className="px-4 py-3 font-mono text-[10px] tabular-nums">{entry.duration_ms.toFixed(1)} ms</td><td className="max-w-sm truncate px-4 py-3 text-[10px]" title={entry.result_summary}>{entry.result_summary || '无摘要'}</td><td className="max-w-32 truncate px-4 py-3 font-mono text-[9px] text-crt-fg-muted" title={entry.trace_id}>{entry.trace_id || '—'}</td></tr>)}{!loading && !data.entries.length ? <tr><td colSpan={6} className="px-4 py-16 text-center text-[12px] text-crt-fg-muted">没有符合条件的审计记录</td></tr> : null}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-crt-border px-4 py-3 text-[10px] text-crt-fg-muted"><span>第 {page} / {pages} 页</span><div className="flex gap-1"><button className="icon-button" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))} aria-label="上一页"><ChevronLeft size={14} /></button><button className="icon-button" disabled={offset + PAGE_SIZE >= data.total} onClick={() => setOffset(offset + PAGE_SIZE)} aria-label="下一页"><ChevronRight size={14} /></button></div></div>
    </div>
  </div>;
}
